//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Order_Cart_Table = new HashSet<Order_Cart_Table>();
            this.Order_Table = new HashSet<Order_Table>();
        }
    
        public int Customer_id { get; set; }

        [Required(ErrorMessage = "please Enter your Email ")]
        [RegularExpression(".+\\@.+\\..+", ErrorMessage ="Please enter a valid Email address")]
        public string Customer_Email { get; set; }

        [Required(ErrorMessage = "please Enter your First name ")]
        public string First_name { get; set; }

        [Required(ErrorMessage = "please Enter your Last name  ")]
        public string Last_name { get; set; }

        [Required(ErrorMessage = "please Enter a password ")]
        public string Password { get; set; }

        [Required(ErrorMessage = "please Enter your Address  ")]
        public string Address { get; set; }

        [Required(ErrorMessage = "please Enter your Phone ")]
        [RegularExpression("/([(]?)([5])([0-9]{2})([)]?)([\\s]?)([0-9]{3})([\\s]?)([0-9]{2})([\\s]?)([0-9]{2})$/g", ErrorMessage = "Please enter a valid Phone number")]
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Cart_Table> Order_Cart_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Table> Order_Table { get; set; }
    }
}
