//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        public int Order_id { get; set; }
        public int Order_Cart_id { get; set; }
        public int Product_id { get; set; }
        public int Customer_id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Products Products { get; set; }
    }
}
